### ISSUE TITLE
Where is the "analysis" folder

### ISSUE THREAD

**Issue by sebawa** [vsoch/wikipedia-equations#1]
In https://github.com/vsoch/wikipedia-equations/blob/8b7bedbc6bb4036501d6974468453464dd11b296/math/mathDomainAnalysis.py#L112
you refer to the "analysis" folder to review how the tokens are mapped. Sadly, I cannot find this folder nor any code where the mapping is done. I would really like to know how you perform this step. Could you update the repo, please?

**Comment by vsoch** [comment]
I just checked locally - This particular repo doesn't have any analysis folder because the intention was just to provide the data. The expected use case was for the user to look at the README for how to generate the model from the data: https://github.com/vsoch/wikipedia-equations/tree/8b7bedbc6bb4036501d6974468453464dd11b296/math#step-3-word2vec-model

Note that the README is specific about this, it says:

> ... **I haven't done that yet**, but instead I've created an example showing how to do this for the math equations. With our equations loaded, we *could* now use the wordfish `TrainEquations` class to take in the list of equations, and generate a model. That comes down to this:

And then I provide the example to build a model.

The notebook [here](https://github.com/vsoch/wikipedia-equations/blob/8b7bedbc6bb4036501d6974468453464dd11b296/statistics/tsne_wikipedia_statistics_analysis.ipynb) also might be helpful - it's large so likely you'll need to run it locally (I can't get it to render in GitHub).  It could just be that I never did this meaningfully so it doesn't exist, sorry I can't be of further help! 

The actual analysis folder in question is in this repository -> https://github.com/vsoch/arxiv-equations/tree/master/wikipedia and I expect that if you use any portion of my work, or this dataset in your analysis, that you cite it appropriately:

https://zenodo.org/record/2538440#.XZtu7nVKhgw

Looking forward to seeing your work!
